### ISSUE TITLE
Update cachelib to 0.1.1

### ISSUE THREAD

**Issue by FollieHiyuki** [gleitz/howdoi#333]
We are still using 0.1 from 2018.
This will help packaging for systems where `pip install howdoi` doesn't work.
Currently if `howdoi` is built with 0.1.1, the program will not work.

**Comment by FollieHiyuki** [comment]
After trying to build the latest version 2.0.12 `howdoi` magically starts working.
This seems like a mistake on my end :)
Though I still want the project to keep its dependencies up to date.

**Comment by FollieHiyuki** [comment]
Oh never mind the issue is still there. It only happens when I use the `--color` flag.

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cachelib 0.1.1 (/usr/lib/python3.9/site-packages), Requirement.parse('cachelib==0.1'), {'howdoi'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bin/howdoi", line 12, in <module>
    sys.exit(command_line_runner())
  File "/usr/lib/python3.9/site-packages/howdoi/howdoi.py", line 719, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/usr/lib/python3.9/site-packages/howdoi/howdoi.py", line 592, in howdoi
    res = _get_answers(args)
  File "/usr/lib/python3.9/site-packages/howdoi/howdoi.py", line 422, in _get_answers
    answer = _get_answer(args, question_links)
  File "/usr/lib/python3.9/site-packages/howdoi/howdoi.py", line 374, in _get_answer
    text = _format_output(args, get_text(instructions.eq(0)))
  File "/usr/lib/python3.9/site-packages/howdoi/howdoi.py", line 308, in _format_output
    lexer = get_lexer_by_name(keyword)
  File "/usr/lib/python3.9/site-packages/pygments/lexers/__init__.py", line 115, in get_lexer_by_name
    for cls in find_plugin_lexers():
  File "/usr/lib/python3.9/site-packages/pygments/plugin.py", line 53, in find_plugin_lexers
    for entrypoint in iter_entry_points(LEXER_ENTRY_POINT):
  File "/usr/lib/python3.9/site-packages/pygments/plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 570, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 583, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'cachelib==0.1' distribution was not found and is required by howdoi
```

**Comment by gleitz** [comment]
Thanks for the report. Will bump the cachelib version and also take a pass over the other dependencies to see if there is anything else we should be updating as well.

**Comment by gleitz** [comment]
Fixed in #343

**Comment by FollieHiyuki** [comment]
@gleitz I think the problem is still there (at least for me, since I build the package myself instead of using `pip`).
I still get the same error regarding `cachelib`.
I don't think I can get `pathlib` to work either. Why don't we use `pathlib2` instead of `pathlib`?

**Comment by gleitz** [comment]
If you can get it working with your system, I'd be happy to accept a PR :)

**Comment by gleitz** [comment]
Perhaps cachelib needs be updated?

https://github.com/gleitz/howdoi/blob/master/requirements/common.txt#L8
https://github.com/gleitz/howdoi/blob/master/setup.py#L71

**Comment by FollieHiyuki** [comment]
> If you can get it working with your system, I'd be happy to accept a PR :)

Sorry I don't know Python really well :( but I will try to help as much as I can

> Perhaps cachelib needs be updated?
> https://github.com/gleitz/howdoi/blob/master/requirements/common.txt#L8
> https://github.com/gleitz/howdoi/blob/master/setup.py#L71

Yes please do so.

The problem still remains with `pathlib` though. We already got `pathlib2` packaged in Void Linux, so packaging `pathlib` will not likely to be accepted (it is not maintained anymore, as stated in their readme). Is there any API breakage that hold us back from using `pathlib2`?

**Comment by FollieHiyuki** [comment]
Sorry for the noise.
My system python environment is horrible, so I mistook the `pathlib` problem :)
I tried rebuilding it again. Changing the `cachelib` version number to 0.1.1 makes the error go away.
I still can't test whether the `-c` option works, since PyGithub is blocking by PyJWT on my distro (another dependencies hell problem) and errors out when I use `-c`.

**Comment by gleitz** [comment]
Yes, `pathlib` should be part of the standard Python distribution. Glad that the update to 0.1.1 of cachelib fixes your issue. If you like, try submitting a PR! I can help you if there are any issues once you open it.

**Comment by FollieHiyuki** [comment]
Thanks for pointing out. I made a PR #356. Can you take a look?
